@extends('layouts.app')
@section('title', 'Admin — Mia Assistente')
@section('content')
<div class="page-heading"><div><span class="page-kicker">PAINEL ADMINISTRATIVO</span><h1>Visão geral</h1><p>Acompanhe a operação e o crescimento da Mia.</p></div><span class="status-pill"><i></i> Sistema operacional</span></div>
<section class="metric-grid"><article class="metric-card"><div class="metric-head"><span>Clientes</span><i class="metric-icon tasks">↗</i></div><strong>{{ $metrics['clients'] }}</strong><p><b>{{ $metrics['active_clients'] }}</b> contas ativas</p></article><article class="metric-card"><div class="metric-head"><span>Lançamentos</span><i class="metric-icon income">R$</i></div><strong>{{ number_format($metrics['finance_records'], 0, ',', '.') }}</strong><p>Registros financeiros</p></article><article class="metric-card"><div class="metric-head"><span>Atividades</span><i class="metric-icon expense">✓</i></div><strong>{{ number_format($metrics['tasks'], 0, ',', '.') }}</strong><p>Tarefas gerenciadas</p></article><article class="metric-card dark-card"><span>Automação</span><strong>Telegram + IA</strong><p>Integração pronta para configurar</p></article></section>
<section class="dashboard-columns admin-columns"><article class="panel"><div class="panel-heading"><div><h2>Novos clientes</h2><p>Cadastros nos últimos meses</p></div></div><div class="admin-chart">@php $chartMax=max((int)$registrations->max(),1); @endphp @forelse($registrations as $label=>$total)<div><span style="height:{{ max(10,($total/$chartMax)*100) }}%"><b>{{ $total }}</b></span><small>{{ \Carbon\Carbon::createFromFormat('Y-m',$label)->translatedFormat('M') }}</small></div>@empty<div class="empty-state"><p>Aguardando novos cadastros.</p></div>@endforelse</div></article>
<article class="panel"><div class="panel-heading"><div><h2>Clientes recentes</h2><p>Últimos cadastros</p></div><a href="{{ route('admin.clients') }}">Ver todos →</a></div><div class="record-list">@foreach($latestClients as $client)<div class="record-row"><span class="avatar small">{{ mb_strtoupper(mb_substr($client->name,0,1)) }}</span><div><strong>{{ $client->name }}</strong><span>{{ $client->email }}</span></div><b class="status-label {{ $client->status }}">{{ $client->status === 'active' ? 'Ativo' : ucfirst($client->status) }}</b></div>@endforeach</div></article></section>
<section class="admin-quick-grid"><a href="{{ route('admin.clients') }}"><span>Clientes</span><strong>Gerenciar acessos →</strong></a><a href="{{ route('admin.categories') }}"><span>Categorias</span><strong>Editar sugestões →</strong></a><a href="{{ route('admin.settings') }}"><span>Integrações</span><strong>Configurar chaves →</strong></a></section>
@endsection
