ProxyPass /mia/ http://127.0.0.1:18088/ connectiontimeout=5 timeout=120
ProxyPassReverse /mia/ http://127.0.0.1:18088/
RedirectMatch 301 ^/mia$ /mia/

<Location "/mia/">
    RequestHeader set X-Forwarded-Prefix "/mia"
    RequestHeader set X-Forwarded-Proto "https"
</Location>
