@extends('layouts.app')
@section('title', 'Atividades — Mia Assistente')
@section('content')
<div class="page-heading"><div><span class="page-kicker">ORGANIZE O SEU DIA</span><h1>Atividades</h1><p>Acompanhe o que está por fazer, em andamento e concluído.</p></div><button class="btn btn-primary" data-modal-open="task-modal">+ Nova atividade</button></div>
<div class="month-switcher standalone"><a href="{{ route('tasks.index', ['month' => $month->copy()->subMonth()->format('Y-m')]) }}">‹</a><strong>{{ ucfirst($month->translatedFormat('F Y')) }}</strong><a href="{{ route('tasks.index', ['month' => $month->copy()->addMonth()->format('Y-m')]) }}">›</a></div>
<section class="kanban">
@foreach([['todo','A fazer',$todo,'#64748b'],['doing','Em execução',$doing,'#f59e0b'],['done','Finalizadas',$done,'#16a34a']] as [$key,$label,$items,$color])
    <div class="kanban-column"><div class="kanban-heading"><span><i style="background:{{ $color }}"></i>{{ $label }}</span><b>{{ $items->count() }}</b></div><div class="kanban-list">
    @forelse($items as $task)<article class="task-card"><div class="task-card-top"><span class="priority {{ $task->priority }}">{{ ['low'=>'Baixa','medium'=>'Média','high'=>'Alta'][$task->priority] }}</span><div class="kebab"><button type="button">•••</button><div><a href="{{ route('tasks.edit', ['task'=>$task, 'month'=>$month->format('Y-m')]) }}">Editar</a><form method="POST" action="{{ route('tasks.destroy', $task) }}" data-confirm="Remover esta atividade?">@csrf @method('DELETE')<button>Excluir</button></form></div></div></div><h3>{{ $task->name }}</h3>@if($task->description)<p>{{ Str::limit($task->description, 110) }}</p>@endif<div class="task-meta"><span><i style="background:{{ $task->category?->color ?? '#94a3b8' }}"></i>{{ $task->category?->name ?? 'Geral' }}</span><span>{{ $task->due_on ? '◷ '.$task->due_on->format('d/m') : 'Sem prazo' }}</span></div>
        <form method="POST" action="{{ route('tasks.status', $task) }}" class="task-status-form">@csrf @method('PATCH')<select name="status" onchange="this.form.submit()"><option value="todo" {{ $task->status==='todo'?'selected':'' }}>A fazer</option><option value="doing" {{ $task->status==='doing'?'selected':'' }}>Em execução</option><option value="done" {{ $task->status==='done'?'selected':'' }}>Finalizada</option></select></form>
    </article>@empty<div class="kanban-empty"><span>○</span><p>Nada por aqui</p></div>@endforelse
    </div></div>
@endforeach
</section>
<div class="modal {{ $editTask ? 'open' : '' }}" id="task-modal" aria-hidden="{{ $editTask ? 'false' : 'true' }}"><div class="modal-backdrop" data-modal-close></div><div class="modal-card"><div class="modal-heading"><div><span class="page-kicker">{{ $editTask ? 'EDITANDO' : 'NOVA ATIVIDADE' }}</span><h2>{{ $editTask ? 'Editar atividade' : 'O que precisa ser feito?' }}</h2></div><button type="button" data-modal-close>×</button></div>
    <form method="POST" action="{{ $editTask ? route('tasks.update', $editTask) : route('tasks.store') }}" class="stack-form">@csrf @if($editTask)@method('PUT')@endif
        <label>Nome da atividade<input name="name" value="{{ old('name', $editTask?->name) }}" placeholder="Ex.: Enviar relatório" required></label><label>Descrição<textarea name="description" rows="3" placeholder="Detalhes importantes...">{{ old('description', $editTask?->description) }}</textarea></label>
        <div class="form-grid"><label>Prioridade<select name="priority"><option value="low" {{ old('priority',$editTask?->priority)==='low'?'selected':'' }}>Baixa</option><option value="medium" {{ old('priority',$editTask?->priority ?? 'medium')==='medium'?'selected':'' }}>Média</option><option value="high" {{ old('priority',$editTask?->priority)==='high'?'selected':'' }}>Alta</option></select></label><label>Status<select name="status"><option value="todo" {{ old('status',$editTask?->status ?? 'todo')==='todo'?'selected':'' }}>A fazer</option><option value="doing" {{ old('status',$editTask?->status)==='doing'?'selected':'' }}>Em execução</option><option value="done" {{ old('status',$editTask?->status)==='done'?'selected':'' }}>Finalizada</option></select></label></div>
        <div class="form-grid"><label>Categoria<select name="category_id"><option value="">Geral</option>@foreach($categories as $category)<option value="{{ $category->id }}" {{ (string)old('category_id',$editTask?->category_id)===(string)$category->id?'selected':'' }}>{{ $category->name }}</option>@endforeach</select></label><label>Prazo<input type="date" name="due_on" value="{{ old('due_on',$editTask?->due_on?->format('Y-m-d')) }}"></label></div>
        <button class="btn btn-primary btn-block" type="submit">{{ $editTask ? 'Salvar alterações' : 'Criar atividade' }}</button>
    </form>
</div></div>
@endsection
